### ISSUE TITLE
./run.sh error :  js.Global.Get undefined 

### ISSUE THREAD

**Issue by huayl** [Chyroc/golang-wasm-example#2]
./run.sh 

make out errors:

clean .wasm files
build ./fogleman_ellipse .wasm file...
# github.com/Chyroc/web
../../github.com/Chyroc/web/document.go:25:16: js.Global.Get undefined (type func() js.Value has no field or method Get)
../../github.com/Chyroc/web/image_data.go:22:16: js.Global.Get undefined (type func() js.Value has no field or method Get)
../../github.com/Chyroc/web/var.go:19:33: js.Global.Get undefined (type func() js.Value has no field or method Get)
../../github.com/Chyroc/web/web.go:6:11: js.Global.Get undefined (type func() js.Value has no field or method Get)
../../github.com/Chyroc/web/window.go:21:16: js.Global.Get undefined (type func() js.Value has no field or method Get)
build ./generate_avatar .wasm file...
# github.com/Chyroc/web
../../github.com/Chyroc/web/document.go:25:16: js.Global.Get undefined (type func() js.Value has no field or method Get)
../../github.com/Chyroc/web/image_data.go:22:16: js.Global.Get undefined (type func() js.Value has no field or method Get)
../../github.com/Chyroc/web/var.go:19:33: js.Global.Get undefined (type func() js.Value has no field or method Get)
../../github.com/Chyroc/web/web.go:6:11: js.Global.Get undefined (type func() js.Value has no field or method Get)
../../github.com/Chyroc/web/window.go:21:16: js.Global.Get undefined (type func() js.Value has no field or method Get)
build ./node_modules .wasm file...
stat node_modules/wasm.go: no such file or directory
build ./plus-one .wasm file...
# command-line-arguments
plus-one/wasm.go:11:27: js.Global.Get undefined (type func() js.Value has no field or method Get)
plus-one/wasm.go:12:22: js.Global.Get undefined (type func() js.Value has no field or method Get)
plus-one/wasm.go:13:23: js.Global.Get undefined (type func() js.Value has no field or method Get)
build ./tank .wasm file...
# github.com/Chyroc/web
../../github.com/Chyroc/web/document.go:25:16: js.Global.Get undefined (type func() js.Value has no field or method Get)
../../github.com/Chyroc/web/image_data.go:22:16: js.Global.Get undefined (type func() js.Value has no field or method Get)
../../github.com/Chyroc/web/var.go:19:33: js.Global.Get undefined (type func() js.Value has no field or method Get)
../../github.com/Chyroc/web/web.go:6:11: js.Global.Get undefined (type func() js.Value has no field or method Get)
../../github.com/Chyroc/web/window.go:21:16: js.Global.Get undefined (type func() js.Value has no field or method Get)

**Comment by huayl** [comment]
myversion is:
go1.11 darwin/amd64

**Comment by chyroc** [comment]
try again?

**Comment by huayl** [comment]
i update code and it is okay now! thanks !
